CREATE TABLE `transactions` (
    id BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
    reference VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_DATE,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_DATE,
    PRIMARY KEY (id)
);